language: generic
script:
  - ./run.sh 1
deploy:
  provider: lambda
  function_name: "ssw"
  region: "us-east-2"
  role: "arn:aws:iam::369401945610:role/service-role/sequence_alignment-role-ruszb1hp"
  runtime: "python3.7"
  memory_size: 1088
  timeout: 180
  module_name: "lambda_function"
  handler_name: "handler"
  zip: "lambdaPackage/upload.zip"
  on:
    tags: true
