language: generic
script:
  - ./run.sh 1
deploy:
  provider: lambda
  function_name: "ssw"
  region: "us-east-1"
  role: "arn:aws:iam::369401945610:role/service-role/sequence_alignment-role-ruszb1hp"
  runtime: "python3.7"
  handler_name: "lambda_function.handler"
  zip: "lambdaPackage/upload.zip"
  on:
    branch: "dev"
