# Python
trigger:
- special
jobs:
- job: runJob
  timeoutInMinutes: 3600 
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
  - script: ./run.sh
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      AZURE: 1
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: './client/performanceData/concurrency1000/trial1/'
      artifactName: ExperimentResults
