version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/python:3.7.3
jobs:
  verify:
    executor: my-executor
    steps:
      - checkout
      - run: pip install boto3     
      - run: cd client && python verify_result.py
workflows:
  version: 2
  experiment:
    jobs:
      - verify

